# Generated by Django 3.2 on 2021-04-26 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_alter_task_worker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='sl',
            new_name='taskid',
        ),
    ]
