# Generated by Django 3.2 on 2021-04-27 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_rename_sl_comment_taskid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='taskid',
            new_name='task',
        ),
    ]
